// <auto-generated />
using System;
using FiveS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditAuditPlan", b =>
                {
                    b.Property<int>("AuditPlansId")
                        .HasColumnType("integer");

                    b.Property<int>("AuditsId")
                        .HasColumnType("integer");

                    b.HasKey("AuditPlansId", "AuditsId");

                    b.HasIndex("AuditsId");

                    b.ToTable("AuditAuditPlan");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditId")
                        .HasColumnType("integer")
                        .HasColumnName("DenetimId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("BolumId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Aciklama");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("integer")
                        .HasColumnName("DirektorlukId");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ResimYolu");

                    b.Property<string>("PlannedActivity")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("PlanlananFaaliyet");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Oncelik");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("SoruId");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Sorumlu");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("SektorId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Durum");

                    b.Property<string>("SuggestedActivity")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("OnerilenFaaliyet");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HedefTarih");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SectorId");

                    b.ToTable("Aksiyonlar", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("BolumId");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Aciklama");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("integer")
                        .HasColumnName("DirektorlukId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Aktif");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AlanAdi");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("SektorId");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Sorumlu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("SectorId");

                    b.ToTable("Alanlar", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Alan");

                    b.Property<string>("AreaSupervisor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("AlanSorumlusu");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DenetimTarihi");

                    b.Property<int>("AuditorId")
                        .HasColumnType("integer")
                        .HasColumnName("DenetciId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("BolumId");

                    b.Property<string>("LevelAchieved")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UlasilanSeviye");

                    b.Property<int>("MaxPossibleScore")
                        .HasColumnType("integer")
                        .HasColumnName("MaksimumPuan");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Notlar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Durum");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("ToplamPuan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("AuditorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Denetimler", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.AuditPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("AlanId");

                    b.Property<int>("AuditorId")
                        .HasColumnType("integer")
                        .HasColumnName("DenetciId");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("KategoriId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("BolumId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PlanAdi");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Notlar");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PlanlananTarih");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Durum");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AuditorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DenetimPlanlari", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.AuditResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuditId")
                        .HasColumnType("integer")
                        .HasColumnName("DenetimId");

                    b.Property<int?>("AuditPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("DenetimPlaniId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("VerilenPuan");

                    b.Property<string>("ImageUrls")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("SoruGorselleri");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("SoruId");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Yanit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("AuditPlanId");

                    b.HasIndex("QuestionId");

                    b.ToTable("DenetimYanitlari", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Aciklama");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Aktif");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("KategoriAdi");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("Sira");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gereksiz malzemelerin ayıklanması",
                            IsActive = true,
                            Name = "1S - Seiri (Ayıklama)",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Her şeyin yerli yerinde olması",
                            IsActive = true,
                            Name = "2S - Seiton (Düzenleme)",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çalışma alanının temiz tutulması",
                            IsActive = true,
                            Name = "3S - Seiso (Temizlik)",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standartların uygulanması",
                            IsActive = true,
                            Name = "4S - Seiketsu (Standartlaştırma)",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Disiplinli çalışma alışkanlığı",
                            IsActive = true,
                            Name = "5S - Shitsuke (Disiplin)",
                            OrderIndex = 5
                        });
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Aciklama");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("integer")
                        .HasColumnName("DirektorlukId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Aktif");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("BolumAdi");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("SektorId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Bolumler_BolumAdi");

                    b.HasIndex("SectorId");

                    b.ToTable("Bolumler", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Aciklama");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Aktif");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DirektorlukAdi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.ToTable("Direktorlukler", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.LevelThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SeviyeAdi");

                    b.Property<decimal>("MaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("MaksimumYuzde");

                    b.Property<decimal>("MinPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("MinimumYuzde");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.ToTable("SeviyeEsikleri", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "Başlangıç S",
                            MaxPercentage = 19.99m,
                            MinPercentage = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "1S",
                            MaxPercentage = 39.99m,
                            MinPercentage = 20m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "2S",
                            MaxPercentage = 59.99m,
                            MinPercentage = 40m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "3S",
                            MaxPercentage = 79.99m,
                            MinPercentage = 60m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "4S",
                            MaxPercentage = 94.99m,
                            MinPercentage = 80m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LevelName = "5S",
                            MaxPercentage = 100m,
                            MinPercentage = 95m
                        });
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Alan");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("KategoriId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Bolum");

                    b.Property<string>("Directorate")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Direktorluk");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Aktif");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("Sira");

                    b.Property<int>("PointsHigh")
                        .HasColumnType("integer")
                        .HasColumnName("YuksekPuan");

                    b.Property<int>("PointsLow")
                        .HasColumnType("integer")
                        .HasColumnName("DusukPuan");

                    b.Property<int>("PointsMedium")
                        .HasColumnType("integer")
                        .HasColumnName("OrtaPuan");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Sektor");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("SoruMetni");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Sorular", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Aciklama");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Aktif");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SektorAdi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.HasKey("Id");

                    b.ToTable("Sektorler", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Anahtar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Deger");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Ayarlar_Anahtar");

                    b.ToTable("Ayarlar", (string)null);
                });

            modelBuilder.Entity("FiveS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("BolumId");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("integer")
                        .HasColumnName("DirektorlukId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Aktif");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SonGiris");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("AdSoyad");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Sifre");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Rol");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("SektorId");

                    b.Property<string>("Sicil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SicilNo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("GuncellemeTarihi");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("KullaniciAdi");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Kullanicilar_Email");

                    b.HasIndex("SectorId");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_Kullanicilar_KullaniciAdi");

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("AuditAuditPlan", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.AuditPlan", null)
                        .WithMany()
                        .HasForeignKey("AuditPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveS.Domain.Entities.Audit", null)
                        .WithMany()
                        .HasForeignKey("AuditsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Action", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Audit", "Audit")
                        .WithMany("Actions")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Aksiyonlar_Denetimler");

                    b.HasOne("FiveS.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Aksiyonlar_Bolumler");

                    b.HasOne("FiveS.Domain.Entities.Directorate", "Directorate")
                        .WithMany()
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Aksiyonlar_Direktorlukler");

                    b.HasOne("FiveS.Domain.Entities.Question", "Question")
                        .WithMany("Actions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Aksiyonlar_Sorular");

                    b.HasOne("FiveS.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Aksiyonlar_Sektorler");

                    b.Navigation("Audit");

                    b.Navigation("Department");

                    b.Navigation("Directorate");

                    b.Navigation("Question");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Area", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Department", "Department")
                        .WithMany("Areas")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Alanlar_Bolumler");

                    b.HasOne("FiveS.Domain.Entities.Directorate", "Directorate")
                        .WithMany("Areas")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiveS.Domain.Entities.Sector", "Sector")
                        .WithMany("Areas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Directorate");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Audit", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.User", "Auditor")
                        .WithMany("Audits")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Denetimler_Kullanicilar");

                    b.HasOne("FiveS.Domain.Entities.Department", "Department")
                        .WithMany("Audits")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Denetimler_Bolumler");

                    b.Navigation("Auditor");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.AuditPlan", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Area", "Area")
                        .WithMany("AuditPlans")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DenetimPlanlari_Alanlar");

                    b.HasOne("FiveS.Domain.Entities.User", "Auditor")
                        .WithMany("AuditPlans")
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DenetimPlanlari_Kullanicilar");

                    b.HasOne("FiveS.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DenetimPlanlari_Kategoriler");

                    b.HasOne("FiveS.Domain.Entities.Department", "Department")
                        .WithMany("AuditPlans")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DenetimPlanlari_Bolumler");

                    b.Navigation("Area");

                    b.Navigation("Auditor");

                    b.Navigation("Category");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.AuditResponse", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Audit", "Audit")
                        .WithMany("Responses")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DenetimYanitlari_Denetimler");

                    b.HasOne("FiveS.Domain.Entities.AuditPlan", "AuditPlan")
                        .WithMany("AuditResponses")
                        .HasForeignKey("AuditPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DenetimYanitlari_DenetimPlanlari");

                    b.HasOne("FiveS.Domain.Entities.Question", "Question")
                        .WithMany("AuditResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DenetimYanitlari_Sorular");

                    b.Navigation("Audit");

                    b.Navigation("AuditPlan");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Department", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Directorate", "Directorate")
                        .WithMany("Departments")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiveS.Domain.Entities.Sector", "Sector")
                        .WithMany("Departments")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Directorate");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Question", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sorular_Kategoriler");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.User", b =>
                {
                    b.HasOne("FiveS.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Kullanicilar_Bolumler");

                    b.HasOne("FiveS.Domain.Entities.Directorate", "Directorate")
                        .WithMany()
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Kullanicilar_Direktorlukler");

                    b.HasOne("FiveS.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Kullanicilar_Sektorler");

                    b.Navigation("Department");

                    b.Navigation("Directorate");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Area", b =>
                {
                    b.Navigation("AuditPlans");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Audit", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.AuditPlan", b =>
                {
                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Department", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("AuditPlans");

                    b.Navigation("Audits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Directorate", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Question", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("AuditResponses");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("FiveS.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditPlans");

                    b.Navigation("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
